

const types = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    FETCH_BINGO_ALL_SUCCESS: 'FETCH_BINGO_ALL_SUCCESS',
    FETCH_BINGO_ALL_FAILD: 'FETCH_BINGO_ALL_FAILD',
    DIAL_BINGO_SUCCESS: 'DIAL_BINGO_SUCCESS',
    DIAL_BINGO_FAILD: 'DIAL_BINGO_FAILD',

    CHECK_BINGO_SUCCESS: 'CHECK_BINGO_SUCCESS',
    CHECK_BINGO_FAILD: 'CHECK_BINGO_FAILD',

}

export default types;